### ISSUE TITLE
H5P ID List Error message

### ISSUE THREAD

**Issue by wboettge** [HBlanco36/xapi-data-analyzer#32] opened 2020-10-28 17:57 UTC
![image003](https://user-images.githubusercontent.com/61607770/97477042-20cd3f00-191d-11eb-8bea-9b0cc6500d27.png)
Bug with invalid ID integers.

**Comment by hwhite36** [comment] 2020-10-28 18:33
couldn't reproduce the error, so I'm closing this issue. I think we probably ended up fixing this inadvertently when we added stricter checks for ElementCollections that didn't actually have any data.

**Closed as completed by hwhite36** 2020-10-28 18:33 UTC
Labels: bug
